---
services:
  db:
    image: postgres:15
    container_name: crdt_pg
    restart: always
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: crdtdb
    ports: [5432:5432]
    volumes: [postgres_data:/var/lib/postgresql/data]
    healthcheck:
      test: [CMD, 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend
    container_name: crdt_backend
    ports: [8080:8080]
    environment:
      DB_HOST: db
      DB_USER: demo
      DB_PASS: demo
      DB_NAME: crdtdb
    depends_on: [db]
  ui:
    build: ./ui
    container_name: crdt_ui
    ports: [4200:80]
    depends_on: [backend]
volumes:
  postgres_data:
